# Copyright 2020 Amazon.com, Inc. or its affiliates
# Copyright 2022 Kuartis.com
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kuartis-virtual-gpu-device-plugin-daemonset
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kuartis-virtual-gpu-device-plugin
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kuartis-virtual-gpu-device-plugin
    spec:
      hostIPC: true
      nodeSelector:
        k8s.kuartis.com/accelerator: vgpu
      tolerations:
        - key: k8s.kuartis.com/vgpu
          operator: Exists
          effect: NoSchedule
      priorityClassName: "system-node-critical"
      initContainers:
        - name: set-compute-mode
          image: nvidia/cuda:11.6.0-runtime-ubuntu20.04
          command: ["nvidia-smi", "-c", "EXCLUSIVE_PROCESS"]
          securityContext:
            capabilities:
              add: ["SYS_ADMIN"]
      containers:
        - image: ghcr.io/kuartis/kuartis-virtual-gpu-device-plugin:0.6.3
          name: kuartis-virtual-gpu-device-plugin-ctr
          command:
            - /usr/bin/virtual-gpu-device-plugin
          args:
            - --vgpu=10
            - --allowmultigpu=false
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 8080
              name: metrics
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
            - name: proc
              mountPath: /host/proc
              readOnly: true
            - mountPath: /var/run/dockershim.sock
              name: dockershimsock
        - image: nvidia/mps
          name: mps
          volumeMounts:
            - name: nvidia-mps
              mountPath: /tmp/nvidia-mps
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: nvidia-mps
          hostPath:
            path: /tmp/nvidia-mps
        - name: proc
          hostPath:
            path: /proc
        - name: dockershimsock
          hostPath:
            path: /var/run/dockershim.sock
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kuartis-virtual-gpu-device-plugin
  name: kuartis-virtual-gpu-device-plugin
  namespace: kube-system
spec:
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: kuartis-virtual-gpu-device-plugin
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: kuartis-virtual-gpu-device-plugin
  name: kuartis-virtual-gpu-device-plugin
  namespace: kube-system
spec:
  endpoints:
    - interval: 15s
      path: /metrics
      port: metrics
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      app.kubernetes.io/name: kuartis-virtual-gpu-device-plugin
